services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: testing
    volumes:
      - ./docker/oracle/setup:/container-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_HOSTNAME: 'localhost'
      KEYCLOAK_FRONTEND_PORT: '8081'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      KEYCLOAK_HOME: '/opt/keycloak'
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'dtm'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
    volumes:
      - ./docker/keycloak:/scripts
    entrypoint: /scripts/docker-entrypoint.sh

  puppet:
    image: slominskir/puppet-show:2.1.1
    hostname: puppet
    container_name: puppet
    ports:
      - "3000:3000"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    hostname: mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"