services:
  oracle:
    extends:
      file: deps.yml
      service: oracle

  keycloak:
    extends:
      file: deps.yml
      service: keycloak

  puppet:
    extends:
      file: deps.yml
      service: puppet

  mailhog:
    extends:
      file: deps.yml
      service: mailhog

  dtm:
    hostname: dtm
    container_name: dtm
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'dtm'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
      KEYCLOAK_FRONTEND_SERVER_URL: 'http://localhost:8081'
      KEYCLOAK_BACKEND_SERVER_URL: 'http://keycloak:8080'
      LOGBOOK_SERVER_URL: 'https://logbooks.jlab.org'
      ORACLE_DATASOURCE: 'dtm'
      ORACLE_SERVER: 'oracle:1521'
      ORACLE_USER: 'DTM_OWNER'
      ORACLE_PASS: 'password'
      ORACLE_SERVICE: 'xepdb1'
      PUPPET_SHOW_SERVER_URL: 'http://puppet:3000'
      BACKEND_SERVER_URL: 'http://dtm:8080'
      FRONTEND_SERVER_URL: 'https://localhost:8443'
      TZ: 'America/New_York'
      DTM_FEEDBACK_SENDER_ADDRESS: 'dtm@example.com'
      DTM_FEEDBACK_TO_ADDRESS_CSV: 'recipient1@example.com,recipient2@example.com'
      DTM_CONTENT_CONTACT: 'bob@example.com'
      DTM_TECHNICAL_CONTACT: 'larry@example.com'
      DTM_DOC_CSV: 'https://github.com/JeffersonLab/dtm|DTM Home,https://ace.jlab.org/cdn/doc/dtm/UserGuide.pdf|User Guide'